services:
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - appointment-app_laravel_network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd  # ✅ Ensure this matches `.env`
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_P@ssw0rd
    ports:
      - "3306:3306"
    networks:
      - appointment-app_laravel_network
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "192.168.0.188:8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - appointment-app_laravel_network
    depends_on:
      - app

networks:
  appointment-app_laravel_network:
    external: true

volumes:
  mysql_data:
